whitelist:
  enabled: true
message:
  join-no-whitelist: "&cВ данный момент вас нету в Whitelist"
  player-not-found: "&c%player% Не найден"
  player-already-whitelisted: "&c%player% Уже в белом списке"
  whitelist-add-player: "&c%player% Был успешно добавлен в Whitelist"
  whitelist-remove-player: "&c%player% Был успешно удалён из Whitelist"
  whitelist-on: "&cWhitelist Был включён"
  whitelist-off: "&cWhitelist Был выключён"
  whitelist-reload: "&cAdvancedWhitelist был перезагружен"
  whitelist-already-on: "&cWhitelist Уже включён"
  whitelist-already-off: "&cWhitelist Уже выключён"
  dont-have-permission: "&cУ вас нету прав на использование данной команды"
in-whitelist:
  - Venterok
  - RuverQ