whitelist:
  enabled: true

message:
  whitelist-action:
    - "&c%player% Был успешно добавлен в Whitelist"
    - "&c%player% Был успешно удалён из Whitelist"
  player-check:
    - "&c%player% находится в белом списке"
    - "&c%player% не находится в белом списке"
  whitelist-enabled:
    - "&cWhitelist Был включён"
    - "&cWhitelist Был выключён"

  join-no-whitelist: "&cВ данный момент вас нету в Whitelist"
  player-not-found: "&c%player% Не найден"
  player-already-whitelisted: "&c%player% Уже в белом списке"
  whitelist-reload: "&cAdvancedWhitelist был перезагружен"
  whitelist-size: "&cВ whitelist находится %whsize% игроков"
  dont-have-permission: "&cУ вас нету прав на использование данной команды"
  command-error: "&Сломалось"

in-whitelist:
  - Venterok
  - TAHOC
