name: AdvancedWhitelist
version: 1.0
main: org.venterok.advancedwhitelist.AdvancedWhitelist
api-version: 1.17
authors: [ Venterok ]
description: Better Minecraft Whitelist
commands:
  advwhitelist:
    description: AdvancedWhitelist Command add/remove/on/off/reload
    permission: AdvancedWhitelist.admin
